version: '2'

services:
    monolithic:
        build: .
        ports:
            - "9399:8080"
        environment:
            - network_file=local.cfg

    cluster:
        build: .
        networks:
            - my_cloud
        links:
            - proxy
            - engine
            - users
            - chat
            - rooms
        command: bash -c "while true; do sleep 1; done"

    proxy:
        build: .
        hostname: proxy
        networks:
            - my_cloud
        ports:
            - "9399:8080"
        command: python3 -u /usr/src/app/sources/Proxy.py
        environment:
            - network_file=cluster.cfg

    engine:
        build: .
        hostname: engine
        networks:
            - my_cloud
        command: python3 -u /usr/src/app/sources/Engine.py
        environment:
            - network_file=cluster.cfg

    users:
        build: .
        networks:
            - my_cloud
        command: python3 -u /usr/src/app/sources/Users.py
        environment:
            - network_file=cluster.cfg

    rooms:
        build: .
        networks:
            - my_cloud
        command: python3 -u /usr/src/app/sources/Rooms.py
        environment:
            - network_file=cluster.cfg

    chat:
        build: .
        networks:
            - my_cloud
        command: python3 -u /usr/src/app/sources/Chat.py
        environment:
            - network_file=cluster.cfg

networks:
    my_cloud: